version: "3.9"

services:
  api:
    image: autumnjolitz/powerscout
    build:
      dockerfile: ./config/Dockerfile
      context: '..'
    networks:
      - frontend
    environment:
      - POWERSCOUT_POSTGRES_URI
    ports:
      - 8080
  database:
    image: autumnjolitz/powerscout-db
    build:
      dockerfile: ./config/Dockerfile.schema
      context: '..'
    ports:
      - 5432

networks:
  frontend:

volumes:
  database: