GRAPHITE_HOSTNAME: localhost
GRAPHITE_PORT: 2004
APC_ENDPOINT: null
APC_USERNAME: null
APC_PASSWORD: null
REDIS_URI: redis://localhost:6379/0
GRAPHITE_FLUSH_PERIOD_SECONDS: 10
MAX_GRAPHITE_QUEUE_LENGTH: 10
LOWEST_GRID_VAC_ALLOWED: 110
POSTGRES_URI: postgres://localhost/powerscout

